add_newline = false
scan_timeout = 10

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$custom\
$sudo\
$time\
$status\
$character"""

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "green"

[git_status]
style = "bold yellow"
staged = '[++\($count\)](green)'
stashed = " pending_stash "
untracked = " untracked_files "
deleted = " deleted_files "
renamed = " renamed_files "
conflicted = " conflicted "
modified = " modifications "

[time]
disabled = false
format = "[$time](bold green)"
time_format = "%T"

